receivers:
  otlp:
    protocols:
      #grpc: 
      #  endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch:

exporters:
  logging:
    loglevel: info
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,jaeger]
    logs:
      receivers: [otlp]
      exporters: [logging,jaeger]